#!/usr/bin/env bash

set -e

osname=$(uname)
inital_dir="$(pwd)"
dotfiles_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

my_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "[dotfiles] $fmt\n" "$@"
}

install_linux() {
  my_echo "checking stow..."
  command -v stow >/dev/null 
  if [ $? != 0 ]; then
    my_echo "installing stow"
    sudo apt-get install -y stow
  else
    my_echo "using stow"
  fi
}

if [ $osname == "Linux" ]; then
  my_echo "Looks like I'm Running on Linux"
  install_linux
else 
  my_echo "I'm not sure how to deal with this OS \"$osname\""
  exit 1
fi

my_echo "changing to $dotfiles_dir"
cd "$dotfiles_dir"

my_echo 'stowing ...'
stow bash
stow zsh
stow git
stow ruby
stow python
stow vscode
stow cinnamon

my_echo "changing to $inital_dir"
cd "$inital_dir"

my_echo '******************************************************************'
my_echo '****   Dotfiles installed! Restart computer for full effect   ****'
my_echo '******************************************************************'
