#!/usr/bin/env bash

set -e

. ./scripts/common/my_echo

# uses stow to manage config files
# https://github.com/aspiers/stow

osname=$(uname)

my_echo 'stowing common apps...'
STOW_SOURCE="$(dirname "${BASH_SOURCE[0]}")/../"
STOW_TAREGET=~
stow="stow -d $STOW_SOURCE -t $STOW_TAREGET "
$stow aliases
$stow asdf
$stow bash
$stow git
$stow python
$stow ruby
# $stow vscode
$stow zsh

if [ $osname == "Linux" ]; then
  my_echo 'stowing linux apps...'
  $stow cinnamon
fi
