#!/usr/bin/env bash

set -e

# uses stow to manage config files
# https://github.com/aspiers/stow

osname=$(uname)
inital_dir="$(pwd)"
dotfiles_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

my_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "[dotfiles] $fmt\n" "$@"
}

my_echo "changing to $dotfiles_dir"
cd "$dotfiles_dir"

my_echo 'stowing common apps...'
stow aliases
stow asdf
stow bash
stow git
stow python
stow ruby
stow vscode
stow zsh

if [ $osname == "Linux" ]; then
  my_echo 'stowing linux apps...'
  ./linux/run_stow
fi

my_echo "changing to $inital_dir"
cd "$inital_dir"
